### ISSUE TITLE
Support node installed via nvm

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/commitplease#49]
See https://github.com/jquery/jquery/issues/2915#issuecomment-185140624

**Comment by jzaefferer** [comment]
@all3fox this would also be a good one. You could start by digging into the issue link, then we can discuss what we can do here.

**Comment by all3fox** [comment]
I read [the husky issue](https://github.com/jquery/jquery/issues/2915#issuecomment-185140624) in jQuery and [the linked issue](https://github.com/jzaefferer/commitplease/issues/47) in commitplease, here are my thoughts:

I tried to reproduce it on my machine: a simple project with `commitplease` and a `5.10.1` version of `node` installed via `nvm`. My commits to this project were being checked as expected. Then I bumped the node version:
```
nvm uninstall 5.10.1
nvm install 5.11
nvm use 5.11
```
Everything was still working. Ok, I cannot reproduce this issue with OS X El Capitan (10.11.3) on my machine (which runs Arch Linux). Another thing: I was doing `git commit` from the command line, not from a GUI app which mgol mentions. Basically, I could not reproduce [his original steps](https://github.com/jzaefferer/commitplease/issues/47#issuecomment-182769545).

The issue itself is addressed [59-87 of the husky repository](https://github.com/typicode/husky/blob/d0c0345ed5b0d68bcbb2766c9ad32ab703a7e31f/src/index.js#L59). As I understand it, somehting similar should be done inside the `commit-msg-hook.js` of commitplease. But I do not feel comfortable doing this change because I cannot reproduce --- cannot know if I fix it or break it :(

Another option is to maybe make commitplease depend on husky. This will mean that husky provides all these git hooks as script options in package.json and commitplease then writes itself as such a script of package.json

**Comment by jzaefferer** [comment]
Okay, I'll see if I can reproduce this on my machine (I'm running OSX 10.11.4).

Meanwhile, I suggest you look at #33 and #34, try to implement both, then we can take those into consideration when designing the new validation options API to support the Angular style guide.

**Comment by jzaefferer** [comment]
Can't tell if this is still an issue, since its been a year, I'm closing.
