### ISSUE TITLE
Add common objections and suggested solutions to readme

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/commitplease#67]
There were some concerns on the Angular PRs that we should address in our readme.

**Comment by all3fox** [comment]
Currently, I have seen just two objectioins:

####  Prohibit `git push` instead of `git commit` if the message has invalid style.

Comes from here: https://github.com/angular/angular/pull/9953

That is hard to implement because we do not know how far back in time `commitplease` has to look to check the commits. And it becomes a bummer if the project decides to adopt commitplease but keep older commit messages as is.

#### We check our commit message style with other tools (or manually) and it works fine

Comes from here: https://github.com/eslint/eslint/issues/6706
And I am not sure how to respond. That is a reasonable reaction :(

Did you have something else in mind? Just I am not sure it is worth adding these to the readme?

**Comment by jzaefferer** [comment]
With #70 under review, I think this can be closed.
