### ISSUE TITLE
Test with gitx

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/commitplease#71]
Got an informal error report where committing with gitx always failed, and the output from commitplease doesn't show up

Project seems to be for osx-only: http://gitx.frim.nl/

@all3fox can you test this?

**Comment by all3fox** [comment]
Since there has already been some other OS X specific problem, I will see what I can do to create a VirtualBox + OS X environment. However, I haven't had any previous experience with that. Do you think OS X 10.6 Snow Leopard will be ok for this test?

Next, gitx seems to be a rather [old project](https://github.com/pieter/gitx) that has at least two viable successors (linked from [its readme](https://github.com/pieter/gitx/wiki)) that have the same name: [first](https://github.com/laullon/gitx) and [second](https://github.com/rowanj/gitx). I will test all of them but it would still be nice to know which one of those is actually used in our case.

**Comment by jzaefferer** [comment]
The feedback I got was for `GitX-dev (rowanj fork)`

**Comment by all3fox** [comment]
@jzaefferer sorry, it appears I cannot test it because I do not have access to any OS X variant. I have tried to install two different OS X versions (10.6.5 and 10.6.8) onto two different PCs via Virtual Box and that did not work out :(

**Comment by jzaefferer** [comment]
Closing, as we can't even test it. And usually this is "their" fault, in that they don't print output from git properly, affecting any related tool.
