### ISSUE TITLE
Should work with any of GitHub's closing keywords

### ISSUE THREAD

**Issue by jhilden** [jzaefferer/commitplease#83]
Got the following validation message:
```
- Invalid ticket reference, must be /^(Closes|Fixes) (.*#|gh-|[A-Z]{2,}-)[0-9]+/
Was: fixes #2004
```

I believe that it should accept lower AND upper case just like GitHub does and it should also accept the other keywords specified here:  https://help.github.com/articles/closing-issues-via-commit-messages/

In addition it would be great if it also accepted the keywords specified by waffle.io https://github.com/waffleio/waffle.io/wiki/FAQs#moving-an-issue-into-in-progress-with-a-pull-request-using-waffles-connect-keywords or provides a way to add them.

**Comment by all3fox** [comment]
Hi @jhilden, thank you for the issue! Corect me if I am wrong:

 1. Github uses: close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved
 1. Waffle.io uses: "connects", "connect to", "connects to", "connected to"

I assume @jhilden is using the jQuery profile. The thing is [those commit guidelines](https://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines) technically limit you to a very specific list of capitalized words (Fixes, Closes and Refs) and *even* prohibit you from cramming several of those into one line (which github allows).

@jzaefferer, I think we should have some kind of a "broad" profile that allows all those keywords and other things. And the more specific profiles (like jQuery) should just sternly warn (but probably not abort commit) when somebody uses things from that "broad" profile (like, non-capitaized "fixes" or several references on one line). Or we just need a "broad" profile and strict specific profiles. What do you think?

**Comment by jzaefferer** [comment]
Since I'm working with @jhilden on the same project, I happen to know that he's using the angular preset.

I think we should simply accept all these references. Currently we blacklist some "bad" variations, but allow anything else. For example, "fixse #123" is allowed, because our blacklist doesn't match that.

As long as we can only blacklist, it must still be up to the maintainer to decide if a message is really valid or not. Now that GitHub makes it easy to change the message when doing a squash+merge, its even more pointless to reject something just because we don't quite know about it.
