### ISSUE TITLE
Display my own guidelines URL

### ISSUE THREAD

**Issue by kishu** [jzaefferer/commitplease#97]
If I set a URL for the my own "[guidelines page](https://github.com/naver/egjs/wiki/Commit-Log-Guidelines)", how about displaying an **see** field when an error occurs?

It based angular's guidelines but there is something else.

so if set like below...
```
{
  "commitplease": {
    ...
    guidelinesUrl: "http://my.own.guidlines/path"  
  }
}
```

when error occurs console displaying ...
```
some error message
...

see http://my.own.guidlines/path
```

**Comment by all3fox** [comment]
Thanks, that looks  reasonable, let's see what @jzaefferer has to say about your idea and my code.

Unfotunately, I did not write any tests because I was too lazy. The `console.log('\nSee')` call happens inside the `runValidate` function which ends with `exit(1)` and therefore cannot be unit-tested like the small-and-nice `sanitize` and `validate` functions can.

The proper way is to refactor that `console.log` from `runValidate` into `validate` but that would probably break many tests and I am scared :)

**Comment by jzaefferer** [comment]
That commit looks good to me! @all3fox can you merge and publish it?

**Comment by all3fox** [comment]
Sorry for the delay, had a new notebook and the fonts/flickering were abysmal. All fixed now but took a lot of time.

@kishu, `2.7.10` is up and you can set custom urls. Feel free to reopen/ask, if something does not work.
